### ISSUE TITLE
Emails not in original machine

### ISSUE THREAD

**Issue by sausagehands** [glymphie/UBF8T346G9Parser#6]
I basically have a backup of a backup because I switched computers. I've attached the errors I keep receiving in terminal. Is there any way to work around these? I'm pretty new at this. 

[olk15parser.pdf](https://github.com/glymphie/UBF8T346G9Parser/files/9824619/olk15parser.pdf)

**Comment by glymphie** [comment]
Can't really give you a concrete answer from this, other than your Outlook database is missing.

I am by no means an Outlook expert myself so I would look into:

- Is 'Main Profile' the account you are trying to recover? Look into `/Users/feed_the_pancake/Library/Group Containers/UBF8T346G9.OfficeOutlook/Outlook 15 Profiles/`
- Where is the Outlook.sqlite database located, if it's still there?
- Do you have read permissions in the `UBF8T346G9.OfficeOutlook` folder?

**Comment by sausagehands** [comment]
Hey, so I think I figured out what the issue is, I'm just not sure how to fix it. The output shows that this folder can't be found.  `/Users/feed_the_pancake/Library/Group Containers/UBF8T346G9.OfficeOutlook/Outlook 15 Profiles/Main Profile/Data/Outlook.sqlite`
It's missing a forward slash between UBF8T346G9.Office and Outlook. It should read `/Users/feed_the_pancake/Library/Group Containers/UBF8T346G9.Office/Outlook/Outlook 15 Profiles/Main Profile/Data/Outlook.sqlite`

**Comment by glymphie** [comment]
Ahh of course, in that case, you could just add the forward slash at the end when providing the path 😄

I'll add a handle for that in the future 🙂

**Comment by sausagehands** [comment]
such a simple solution. i was definitely overthinking it 🤦🏻‍♀️
